Repository jenkinsci/coverage-plugin, pull requests merged in 2024-06, with the labels that each got.

#170 Enable quality monitor
  .github/workflows/quality-monitor.yml
Labels: internal

#173 [JENKINS-73175] Improve handling of duplicate nodes
  plugin/pom.xml
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorderITest.java
  ui-tests/src/main/java/io/jenkins/plugins/coverage/CoverageReport.java
  ui-tests/src/main/java/io/jenkins/plugins/coverage/CoverageSummary.java
  ui-tests/src/main/java/io/jenkins/plugins/coverage/publisher/Adapter.java
  ui-tests/src/test/java/io/jenkins/plugins/coverage/CoverageReportTest.java
  ui-tests/src/test/java/io/jenkins/plugins/coverage/MainPanelTest.java
Labels: enhancement

#153 Add coverage metrics from VectorCAST
  README.md
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/CoverageSeriesBuilder.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/CoverageTrendChart.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/model/ElementFormatter.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/source/CoverageSourcePrinter.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/source/SourceCodePainter.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/source/VectorCastSourcePrinter.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageBuildAction.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisher.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTableModel.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTool.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel.java
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/model/Messages.properties
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageMetricColumn/help-metric.html
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageQualityGate/help-metric.html
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/Messages.properties
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/AbstractCoverageTest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisherTest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoveragePluginITest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorderITest.java
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-coverage-publisher-quality-gate-overview.checks-expected-result
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-coverage-publisher-quality-gate.checks-expected-result
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-coverage-publisher-s+b-details.checks-expected-result
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-coverage-publisher-s+b-overview.checks-expected-result
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-coverage-publisher-s+mcdc+fcc-details.checks-expected-result
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-coverage-publisher-s+mcdc+fcc-overview.checks-expected-result
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-coverage-publisher-s+mcdc-details.checks-expected-result
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-coverage-publisher-s+mcdc-overview.checks-expected-result
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-coverage-publisher-summary.checks-expected-result
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-duplicate-methods-statement-mcdc-fcc.xml
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-statement-branch.xml
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-statement-mcdc-fcc.xml
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-statement-mcdc.xml
  ui-tests/src/main/java/io/jenkins/plugins/coverage/publisher/threshold/GlobalThreshold.java
Labels: feature

#184 Do not show method coverage in trend by default
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/CoverageSeriesBuilder.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/CoverageTrendChart.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/charts/CoverageSeriesBuilderTest.java
Labels: bug
