Repository jenkinsci/coverage-plugin, pull requests merged in 2024-02, with the labels that each got.

#85 CSP: Extract inline JS into an adjunct
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/pit.yml
  plugin/src/main/resources/coverage/configuration.properties
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel/index.jelly
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel/init-view-model.js
Labels: internal

#77 [JENKINS-72566] Use reference job API with forensics plugin
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/color/ColorProvider.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/restapi/CoverageApi.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisher.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageQualityGate.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorder.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageReportScanner.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageReporter.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageStep.java
  plugin/src/main/resources/coverage/configuration.properties
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageQualityGate/config.properties
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageQualityGate/help-criticality.html
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageTool/help-pattern.html
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/Messages.properties
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/AbstractCoverageITest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/AbstractModifiedFilesCoverageTest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/restapi/CoverageApiITest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoveragePluginITest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageQualityGateEvaluatorTest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/DeltaComputationITest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/GitForensicsITest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/QualityGateITest.java
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/opencover-with-bom.xml
Labels: bug

#89 Fix name of `proxy` variable
  plugin/pom.xml
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel/init-view-model.js
  plugin/src/main/webapp/js/view-model.js
Labels: bug

#92 [JENKINS-72770] Add example for reference builds with old default logic
  README.md
Labels: documentation

#95 Bump version of coverage-model to 0.41.0
  plugin/pom.xml
Labels: bug
