Repository jenkinsci/coverage-plugin, pull requests merged in 2024-01, with the labels that each got.

#56 Add a tooltip with the full path for a file name table cell
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTableModel.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModelTest.java
Labels: enhancement

#60 Add support for OpenCover
  README.md
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CodeDeltaCalculator.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTool.java
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/Messages.properties
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoveragePluginITest.java
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/opencover.xml
  ui-tests/doc/dependency-graph.puml
Labels: feature

#57 Enable ArcMutate
  .github/workflows/coverage.yml
  .github/workflows/pit.yml
  cdg-pitest-licence.txt
  plugin/pom.xml
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageXmlStreamITest.java
Labels: internal

#66 Include NUnit parser from coverage-model
  README.md
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTool.java
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/Messages.properties
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoveragePluginITest.java
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/nunit.xml
Labels: feature

#72 Add support for XUnit .NET format
  README.md
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTool.java
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/Messages.properties
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoveragePluginITest.java
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/xunit.xml
Labels: feature
