Repository jenkinsci/coverage-plugin, pull requests merged in 2025-08, with the labels that each got.

#467 Update not available text
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/Messages.properties
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/source/SourceCodeITest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoveragePluginITest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModelTest.java
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/coverage-publisher-details.checks-expected-result
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-coverage-publisher-s+b-details.checks-expected-result
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-coverage-publisher-s+mcdc+fcc-details.checks-expected-result
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/vectorcast-coverage-publisher-s+mcdc-details.checks-expected-result
Labels: internal

#466 Use Jenkins cards in all views
  plugin/src/main/resources/coverage/coverage-table.jelly
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/source/SourceViewModel/index.jelly
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel/index.jelly
Labels: enhancement

#470 [JENKINS-75517][JENKINS-75516] Remove tooltips for columns
  plugin/src/main/resources/coverage/coverage-summary.jelly
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageMetricColumn/column.jelly
Labels: bug

#465 Add option to disable coverage column by default
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/CoverageAppearanceGlobalConfiguration.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageMetricColumn.java
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/CoverageAppearanceGlobalConfiguration/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/CoverageAppearanceGlobalConfiguration/help-enableColumnByDefault.html
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/CoverageAppearanceGlobalConfigurationTest.java
Labels: enhancement

#471 Add additional configuration options for coverage column
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/CoverageAppearanceGlobalConfiguration.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageAppearanceConfiguration.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageMetricColumn.java
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/CoverageAppearanceGlobalConfiguration/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/CoverageAppearanceGlobalConfiguration/help-enableColumnByDefault.html
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageAppearanceConfiguration/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageAppearanceConfiguration/config.properties
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageAppearanceConfiguration/help-defaultMetric.html
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageAppearanceConfiguration/help-defaultName.html
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageAppearanceConfiguration/help-enableColumnByDefault.html
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageMetricColumn/columnHeader.jelly
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/CoverageAppearanceGlobalConfigurationTest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageAppearanceConfigurationTest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageMetricColumnTest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/JobDslITest.java
  plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/column.yaml
Labels: enhancement

#474 [JENKINS-73975] Hide delta header if not applicable
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageBuildAction.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageBuildActionTest.java
Labels: bug

#481 Ignore UI tests during release
  pom.xml
Labels: internal

#482 Enable UI tests with profile CI
  pom.xml
Labels: internal

#485 Skip deployment only for parent module
  pom.xml
Labels: bug

#487 Skip deployment in parent
  plugin/pom.xml
  pom.xml
Labels: bug
