Repository jenkinsci/coverage-plugin, pull requests merged in 2025-02, with the labels that each got.

#334 Cleanup deprecated code
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel.java
Labels: internal

#326 Depends on jsoup API plugin
  plugin/pom.xml
Labels: dependencies

#338 Add metric and style customization of trend charts
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/CoverageSeriesBuilder.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/CoverageTrendChart.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/MetricSeriesBuilder.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/MetricsTrendChart.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/TrendChart.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageBuildAction.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageJobAction.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/TrendChartFactory.java
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageJobAction/configure-trend.js
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageJobAction/floatingBox.jelly
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel/index.jelly
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel/index.properties
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel/init-view-model.js
  plugin/src/main/webapp/js/view-model.js
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/charts/CoverageSeriesBuilderTest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageJobActionTest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModelTest.java
  plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/TrendChartFactoryTest.java
Labels: feature

#341 [JENKINS-75323] Fix wrong documentation of metrics selection in column and quality gate
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageMetricColumn/help-metric.html
  plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageQualityGate/help-metric.html
Labels: documentation

#342 Use the latest version of ECharts
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/CoverageTrendChart.java
  plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/MetricsTrendChart.java
Labels: internal
